name: Count courses

on:
  push:
  pull_request:

jobs:
  courseCounter:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Get the number of courses
        run: |
          echo "NCOURSES=`grep -c "\[website\]" README.md`" >> $GITHUB_ENV
      - name: Create the Badge
        uses: schneegans/dynamic-badges-action@v1.6.0
        with:
          auth: ${{ secrets.GIST_SECRET }}
          gistID: 5dd50ff10dbb3fe3222aa8ac658878bf
          filename: ncourses.json
          label: "# courses with website"
          message: ${{ env.NCOURSES }}
          color: orange
